wafflestudio/seminar-2022

README.md
React 세미나는 자바스크립트 중심으로 진행할 예정입니다!
=> change react language to javascript

seminar-list.md
=> 유주성 django세미나 신청합니다

seminar-list.md
=>  장승현 django 세미나 신청합니다

seminar-list.md
=> 백민홍 react 세미나 신청합니다

seminar-list.md
=> 김기성 Django 세미나 신청합니다

seminar-list.md
=> 김민중 django 세미나 신청합니다

seminar-list.md
=> 이수현 android 세미나 신청합니다.

seminar-list.md
=> 노현서 Django 세미나 신청합니다.

seminar-list.md
=> 정택진 Spring 세미나 신청합니다

seminar-list.md
서민후 Django 세미나 신청합니다
1지망 : Django
2지망 : React
3지망 : Android
=> 서민후 Django 세미나 신청합니다

seminar-list.md
=> 제갈준영 Spring 세미나 신청합니다

seminar-list.md
=> 김재영 Django 신청합니다

seminar-list.md
=> 박용주 Django 세미나 신청합니다

seminar-list.md
=> 윤소영 spring 세미나 신청합니다

seminar-list.md
=> 변준섭 spring 세미나 신청합니다. 

seminar-list.md
=> 유창민 react 세미나 신청합니다

seminar-list.md
=> 김도영 Django 세미나 신청합니다

seminar-list.md
=> 신제민 spring 세미나 신청합니다.

seminar-list.md
=> 노우석 spring 세미나 신청합니다

seminar-list.md
=> 조성규 Spring 세미나 신청합니다

seminar-list.md
1지망 react, 2지망 android, 3지망 ios입니다.
감사합니다.
=> 조유진 react 세미나 신청합니다

seminar-list.md
=> 임찬솔 react 세미나 신청합니다

seminar-list.md
=> 조용찬 Spring 세미나 신청합니다

seminar-list.md
=> 이희승 Django 신청합니다.

seminar-list.md
=> 송동엽 android 신청합니다.

seminar-list.md
=> 한우현 react 세미나 신청합니다.

seminar-list.md
=> 김동한 react 세미나 신청합니다

seminar-list.md
=> 오준석 iOS 세미나 신청합니다

seminar-list.md
=> 김하늘 react 세미나 신청합니다

seminar-list.md
=> 서민균 react 세미나 신청합니다

seminar-list.md
=> 최재훈 android 신청합니다.

seminar-list.md
Signed-off-by: Hyunsu Go <hsmail02@snu.ac.kr>
=> 고현수 react 세미나 신청합니다

seminar-list.md
세미나 시간이 안 맞아 3순위 android에서 ios로 변경하였습니다.
=> 손유진 react 세미나 신청합니다

seminar-list.md
3지망 모두 안 되면  android 세미나 신청 하겠습니다.
=> 박지형 react 세미나 신청합니다.

seminar-list.md
=> 안진영 react 세미나 신청합니다

react/seminar-0/README.md, react/seminar-0/assigment-0A-example/index.html, react/seminar-0/assigment-0A-example/script.js, react/seminar-0/assigment-0A-example/style.css, react/seminar-0/assigment-0A-example/waffle-logo.svg
=> add assignment-0A-example

react/seminar-1/assignment-1-example/src/App.css, react/seminar-1/assignment-1-example/src/App.js, react/seminar-1/assignment-1-example/src/components/Modal.css
=> add assignment-1 modal transition

react/seminar-3/why-async/src/App.js
=> update why-async example
